---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cert-manager-selfservice.fullname" . }}
  labels:
    {{- include "cert-manager-selfservice.labels" . | nindent 4 }}
    app.kubernetes.io/component: selfservice
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "cert-manager-selfservice.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cert-manager-selfservice.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "cert-manager-selfservice.fullname" . }}
      containers:
        - name: selfservice
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if (not (empty .Values.image.pullSecrets)) }}
          imagePullSecrets:
            {{- range .Values.image.pullSecrets }}
            - name: {{ . }}
            {{- end }}
          {{- end }}
          args:
            - server
            {{- if .Values.selfservice.debug }}
            - --debug
            {{- end }}
            {{- if .Values.selfservice.auth.enabled }}
            - --auth-username={{ include "cert-manager-selfservice.tplvalues.render" ( dict "value" .Values.selfservice.auth.username "context" $) }}
            - --auth-password={{ include "cert-manager-selfservice.tplvalues.render" ( dict "value" .Values.selfservice.auth.password "context" $) }}
            {{- end }}
            {{- if .Values.metrics.enabled }}
            - --metrics-port={{ .Values.metrics.port }}
            {{- end }}
            - --port={{ .Values.service.port }}
            - --manager-id={{ include "cert-manager-selfservice.tplvalues.render" ( dict "value" .Values.selfservice.managerId "context" $) }}
            - --issuer-kind={{ .Values.selfservice.issuer.kind }}
            - --issuer-name={{ .Values.selfservice.issuer.name }}
            - --cleanup-hours={{ .Values.selfservice.cleanup.hours }}
            {{- if not .Values.selfservice.cleanup.enabled }}
            - --no-cleanup
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            {{- if .Values.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
              protocol: TCP
            {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}