apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cert-manager-selfservice.fullname" . }}
  labels:
    {{- include "cert-manager-selfservice.labels" . | nindent 4 }}
    app.kubernetes.io/component: serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "cert-manager-selfservice.fullname" . }}
rules:
  - apiGroups:
      - ""
      - "cert-manager.io"
    resources:
      - "secrets"
      - "certificates"
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cert-manager-selfservice.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "cert-manager-selfservice.fullname" . }}
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "cert-manager-selfservice.fullname" . }}
    namespace: {{ .Release.Namespace }}