apiVersion: v1
kind: Service
metadata:
  name: {{ include "cert-manager-selfservice.fullname" . }}
  labels:
    {{- include "cert-manager-selfservice.labels" . | nindent 4 }}
    app.kubernetes.io/component: selfservice-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.port }}
      name: metrics
      targetPort: metrics
      protocol: TCP
    {{- end }}
  selector:
    {{- include "cert-manager-selfservice.selectorLabels" . | nindent 4 }}