{{- if and .Values.hetzner.token .Values.hetzner.email }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "cert-manager-webhook-hetzner.fullname" . }}-default
  labels:
    {{- include "cert-manager-webhook-hetzner.labels" . | nindent 4 }}
    app.kubernetes.io/component: default-cluster-issuer
spec:
  acme:
    # The ACME server URL
    server: {{ .Values.hetzner.acmeServer }}

    # Email address used for ACME registration
    email: {{ .Values.hetzner.email }}

    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: {{ include "cert-manager-webhook-hetzner.fullname" . }}-default-secret

    solvers:
      - dns01:
          webhook:
            # This group needs to be configured when installing the helm package, otherwise the webhook won't have permission to create an ACME challenge for this API group.
            groupName: {{ .Values.groupName }}
            solverName: hetzner
            config:
              secretName: {{ include "cert-manager-webhook-hetzner.fullname" . }}-default-secret
              apiUrl: https://dns.hetzner.com/api/v1
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cert-manager-webhook-hetzner.fullname" . }}-default-secret
  labels:
    {{- include "cert-manager-webhook-hetzner.labels" . | nindent 4 }}
    app.kubernetes.io/component: default-cluster-issuer-secret
type: Opaque
data:
  api-key: {{ .Values.hetzner.token | b64enc | quote }}
{{- end }}