---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cert-manager-webhook-hetzner.fullname" . }}
  labels:
    {{- include "cert-manager-webhook-hetzner.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "cert-manager-webhook-hetzner.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cert-manager-webhook-hetzner.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "cert-manager-webhook-hetzner.fullname" . }}
      containers:
        - name: webhook-hetzner
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --tls-cert-file=/tls/tls.crt
            - --tls-private-key-file=/tls/tls.key
          env:
            - name: GROUP_NAME
              value: {{ .Values.groupName | quote }}
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          volumeMounts:
            - name: certs
              mountPath: /tls
              readOnly: true
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: certs
          secret:
            secretName: {{ include "cert-manager-webhook-hetzner.servingCertificate" . }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}