apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cert-manager-webhook-hetzner.fullname" . }}
  labels:
    {{- include "cert-manager-webhook-hetzner.labels" . | nindent 4 }}
    app.kubernetes.io/component: serviceaccount
---
# Grant the webhook permission to read the ConfigMap containing the Kubernetes
# apiserver's requestheader-ca-certificate.
# This ConfigMap is automatically created by the Kubernetes apiserver.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cert-manager-webhook-hetzner.fullname" . }}:webhook-authentication-reader
  namespace: kube-system
  labels:
    {{- include "cert-manager-webhook-hetzner.labels" . | nindent 4 }}
    app.kubernetes.io/component: rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "cert-manager-webhook-hetzner.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
# apiserver gets the auth-delegator role to delegate auth decisions to
# the core apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cert-manager-webhook-hetzner.fullname" . }}:auth-delegator
  labels:
    {{- include "cert-manager-webhook-hetzner.labels" . | nindent 4 }}
    app.kubernetes.io/component: clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "cert-manager-webhook-hetzner.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
# Grant cert-manager permission to validate using our apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cert-manager-webhook-hetzner.fullname" . }}:domain-solver
  labels:
    {{- include "cert-manager-webhook-hetzner.labels" . | nindent 4 }}
    app.kubernetes.io/component: clusterole
rules:
  - apiGroups:
      - {{ .Values.groupName }}
    resources:
      - '*'
    verbs:
      - 'create'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cert-manager-webhook-hetzner.fullname" . }}:domain-solver
  labels:
    {{- include "cert-manager-webhook-hetzner.labels" . | nindent 4 }}
    app.kubernetes.io/component: clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cert-manager-webhook-hetzner.fullname" . }}:domain-solver
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ .Values.certManager.serviceAccountName }}
    namespace: {{ .Values.certManager.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "cert-manager-webhook-hetzner.fullname" . }}:secret-reader
rules:
  - apiGroups:
      - ""
    resources:
      - "secrets"
    {{- if or (and .Values.hetzner.token .Values.hetzner.email) .Values.secretName }}
    resourceNames:
    {{- with .Values.secretName }}
    {{ toYaml . | indent 6 }}
    {{- end }}
    {{- if and .Values.hetzner.token .Values.hetzner.email }}
      - {{ include "cert-manager-webhook-hetzner.fullname" . }}-default-hetzner
      - {{ include "cert-manager-webhook-hetzner.fullname" . }}-default-secret
    {{- end }}
    {{- end }}
    verbs:
      - "get"
      - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cert-manager-webhook-hetzner.fullname" . }}:secret-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "cert-manager-webhook-hetzner.fullname" . }}:secret-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "cert-manager-webhook-hetzner.fullname" . }}
    namespace: {{ .Release.Namespace }}