apiVersion: v1
kind: Service
metadata:
  name: {{ include "cert-manager-webhook-hetzner.fullname" . }}
  labels:
    {{- include "cert-manager-webhook-hetzner.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "cert-manager-webhook-hetzner.selectorLabels" . | nindent 4 }}