## @section Common parameters

## @param nameOverride String to partially override common.names.fullname
nameOverride: ""
## @param fullnameOverride String to fully override common.names.fullname
fullnameOverride: ""

## @section Cert-Manager-Selfservice Deployment parameters

## cert-manager-selfservice Image version
## ref: https://github.com/Mario-F/cert-manager-selfservice/pkgs/container/cert-manager-selfservice
## @param image.repository cert-manager-selfservice image repository
## @param image.tag [string] cert-manager-selfservice image tag (default to AppVersion)
## @param image.pullPolicy cert-manager-selfservice image pull policy
## @param image.pullSecrets Specify docker-registry secret names as an array
##
image:
  repository: docker pull buanet/iobroker
  pullPolicy: IfNotPresent
  pullSecrets: []

## @section Additional features parameters

## @param templates [array] See templates section for explanation
templates: []
  # - enabled: true
  #   content: |
  #     apiVersion: v1
  #     kind: ConfigMap
  #     metadata:
  #       name: {{ include "parent.fullname" . }}-additional
  #       labels:
  #         {{- include "parent.labels" . | nindent 4 }}
  #     data:
  #       example.data: |
  #         nothing special here
  #         out