{{- $fullName := include "pvc-exporter.fullname" . -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $fullName }}-cr
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - 'get'
  - 'list'
  - 'watch'
- nonResourceURLs:
  - '*'
  verbs:
  - 'get'
  - 'list'
  - 'watch'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $fullName }}-crbinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $fullName }}-cr
subjects:
- kind: ServiceAccount
  name: {{ include "pvc-exporter.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pvc-exporter.serviceAccountName" . }}
{{- end }}