{{- $fullName := include "pvc-exporter.fullname" . -}}
{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ $fullName }}
    {{- if .Values.serviceMonitor.additionalLabels }}
    {{- .Values.serviceMonitor.additionalLabels | nindent 4 }}
    {{- end }}
spec:
  jobLabel: app
  selector:
    matchLabels:
      app: {{ $fullName }}
  endpoints:
    - interval: {{ .Values.scrapeInterval }}s
      targetPort: http-metrics
      scheme: http
      path: /
{{- end}}