image:
  repository: ghcr.io/mario-f/pvc-exporter
  pullPolicy: IfNotPresent
  pullSecrets: []

serviceAccount:
  create: false

scrapeInterval: 15

pvcMapper:
  replicaCount: 1
  metricsPort: 8849
  extraArgs: []
  resources:
    requests:
      cpu: 50m
      memory: 50Mi
    limits:
      cpu: 500m
      memory: 200Mi

pvcScanner:
  metricsPort: 8848
  extraArgs: []
  resources:
    requests:
      cpu: 50m
      memory: 50Mi
    limits:
      cpu: 500m
      memory: 200Mi

serviceMonitor:
  enabled: false
  additionalLabels: {}

prometheusRule:
  enabled: false
  additionalLabels: {}
  percent:
    warning: 0.7
    critical: 0.9
