image:
  repository: ghcr.io/mario-f/pvc-exporter
  pullPolicy: IfNotPresent
  pullSecrets: []

serviceAccount:
  create: false

scrapeInterval: 15

pvcMapper:
  replicaCount: 1
  metricsPort: 8849
  extraArgs: []
  resources:
    requests:
      cpu: 100m
      memory: 50Mi
    limits:
      cpu: 1000m
      memory: 200Mi

pvcScanner:
  metricsPort: 8848
  extraArgs: []
  resources:
    requests:
      cpu: 50m
      memory: 50Mi
    limits:
      cpu: 500m
      memory: 200Mi

dashboard:
  enabled: true
  labels:
    grafana_dashboard: "1"
  uid: "b064425af1e711eb"
  title: "Kubernetes / Persistent Volumes (PVC-Exporter)"
  datasource: "-- Grafana --"
  timezone: "UTC"

serviceMonitor:
  enabled: false
  additionalLabels: {}

prometheusRule:
  enabled: false
  additionalLabels: { }
  thresholds:
    absolute:
      - percentage: 30
        for: 1h
        labels:
          severity: warning
      - percentage: 10
        for: 15m
        labels:
          severity: critical
    predictive:
      - interval: 6h
        target: 96h
        labels:
          severity: warning
      - interval: 1h
        target: 24h
        labels:
          severity: critical

raw:
  enabled: false
