## @section Common parameters

## @param nameOverride String to partially override common.names.fullname
##
nameOverride: ""
## @param fullnameOverride String to fully override common.names.fullname
##
fullnameOverride: ""

## @section Cert-Manager-Selfservice Configuration parameters

## cert-manager-selfservice Configuration
## @param selfservice.certPrefix Prefix for certificate ressources
## @param selfservice.issuer.kind The cert-manager issuer type to use
## @param selfservice.issuer.name The name of cert-manager issuer to use
## @param selfservice.debug Will set debug loglevel in selfservice
selfservice:
  certPrefix: "{{ .Release.Name }}"
  issuer:
    kind: ClusterIssuer
    name: default-issuer
  debug: false

## @section Cert-Manager-Selfservice Deployment parameters

## cert-manager-selfservice Image version
## ref: https://github.com/Mario-F/cert-manager-selfservice/pkgs/container/cert-manager-selfservice
## @param image.repository cert-manager-selfservice image repository
## @param image.tag [string] cert-manager-selfservice image tag (default to AppVersion)
## @param image.pullPolicy cert-manager-selfservice image pull policy
## @param image.pullSecrets Specify docker-registry secret names as an array
##
image:
  repository: ghcr.io/mario-f/cert-manager-selfservice
  pullPolicy: IfNotPresent
  pullSecrets: []

## @param nodeSelector Node labels for pod assignment.
## Ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}
## @param tolerations Tolerations for pod assignment.
## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []

## cert-manager-selfservice containers' resource requests and limits
## ref: https://kubernetes.io/docs/user-guide/compute-resources/
## @param resources.limits The resources limits for the cert-manager-selfservice container
## @param resources.requests The requested resources for the cert-manager-selfservice container
##
resources:
  ## Example:
  ## limits:
  ##    cpu: 200m
  ##    memory: 256Mi
  limits: {}
  ## Examples:
  ## requests:
  ##    cpu: 50m
  ##    memory: 64Mi
  requests: {}

## @section Traffic exposure parameters

## cert-manager-selfservice service properties
## @param service.type Service type
## @param service.port Service HTTP port
##
service:
  type: ClusterIP
  port: 5080

## Configure the ingress resource
## ref: https://kubernetes.io/docs/user-guide/ingress/
##
## @skip ingress
ingress:
  enabled: false
  # class: nginx # by ingress.spec.ingressClassName
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts: []
  #  - host: chart-example.local
  #    paths:
  #     - path: /
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

## @section Additional features parameters

## @param templates [array] See templates section for explanation
templates: []
  # - enabled: true
  #   content: |
  #     apiVersion: v1
  #     kind: ConfigMap
  #     metadata:
  #       name: {{ include "parent.fullname" . }}-additional
  #       labels:
  #         {{- include "parent.labels" . | nindent 4 }}
  #     data:
  #       example.data: |
  #         nothing special here
  #         out